baseURL = "http://example.org/"
languageCode = "it-IT"
title = "Agorà Ludica"

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true